# .github/workflows/download-bandcamp.yml
name: Download Bandcamp Audio

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Bandcamp のトラック／アルバム URL'
        required: true
        default: ''

jobs:
  download-and-commit:
    name: ダウンロードしてコミット
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg  # ffmpeg と ffprobe がここに含まれます

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip install yt-dlp

      - name: Prepare output directory
        run: mkdir -p audio

      - name: Download audio from Bandcamp
        run: |
          yt-dlp \
            --extract-audio \
            --audio-format mp3 \
            --audio-quality 0 \
            --output 'audio/%(title)s.%(ext)s' \
            "${{ github.event.inputs.url }}"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add downloaded files
        run: git add audio/

      - name: Commit & Push changes
        run: |
          if ! git diff --cached --quiet; then
            git commit -m "Add audio from Bandcamp: ${{ github.event.inputs.url }}"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No new files to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
